version: '3.8'

services:
  next-ruts-news:
    image: registry.rmutsv.app/panuwat.n/node:next-news-ruts
    networks:
      - public
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      # Timezone
      - TZ=Asia/Bangkok
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0

    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.next-ruts-news.entrypoints: websecure
        traefik.http.routers.next-ruts-news.rule: Host(`news.web.rmutsv.ac.th`)
        traefik.http.routers.next-ruts-news.tls.certresolver: myresolver
        traefik.http.services.next-ruts-news.loadbalancer.server.port: '3000'

networks:
  public:
    external: true
